MVC-model/Controllers/OrderController.cs
using Entity;
using Microsoft.AspNetCore.Mvc;
using MVC_model.Models;
using Service;
using Service.Implementation;

namespace MVC_model.Controllers
{
    public class OrderController : Controller
    {
        private IOrderService _orderService;
        private IOrderDetailService _orderDetailService;
        public OrderController(IOrderService orderService, IOrderDetailService orderDetailService)
        {
            _orderService = orderService;
            _orderDetailService = orderDetailService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = _orderService.GetAll().Select(order => new IndexOrderViewModel
            {
                orderID = order.orderID,
                OrderDate = order.OrderDate,
                FirstName = order.FirstName,
                LastName = order.LastName,
                Address = order.Address,
                Phone = order.Phone,
                Email = order.Email,
                Total = order.Total,
                paymentID = order.paymentID,
                //OrderDetails = order.OrderDetails,
            }).ToList();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new CreateOrderViewModel();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateOrderViewModel model)
        {
            if (ModelState.IsValid)
            {
                var order = new Order
                {
                    orderID = model.orderID,
                    OrderDate = model.OrderDate,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Address = model.Address,
                    Phone = model.Phone,
                    Email = model.Email,
                    Total = model.Total,
                    paymentID = model.paymentID,
                    //OrderDetails = model.OrderDetails
                };
            }
            return View();
        }
        [HttpGet]
        public IActionResult Detail(string id)
        {
            
            var order = _orderService.GetById(id);
            if (order == null)
            {
                return NotFound();
            }
            var model = new DetailOrderViewModel
            {
                orderID = order.orderID,
                OrderDate = order.OrderDate,
                FirstName = order.FirstName,
                LastName = order.LastName,
                Address = order.Address,
                Phone = order.Phone,
                Email = order.Email,
                Total = order.Total,
                paymentID = order.paymentID,
                listItem = _orderDetailService.getOrderDetail(order.orderID),
            };
            return View(model);
        }
    }
}

MVC-model/Controllers/PaymentController.cs
using Entity;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Mvc;
using MVC_model.Models;
using Service;
using Service.Implementation;
using System.Security.Claims;

namespace MVC_model.Controllers
{
    public class PaymentController : Controller
    {
        private IPaymentService _paymentService;
        private IWebHostEnvironment _webHostEnvironment;
        private IItemService _itemService;
        private IProductService _productService;
        private IOrderService _orderService;
        private IOrderDetailService _orderDetailService;
        private IUserService _userService;
        public PaymentController(
            IPaymentService paymentService,
            IWebHostEnvironment webHostEnvironment, 
            IItemService itemService, 
            IProductService productService,
            IOrderService orderService,
            IOrderDetailService orderDetailService,
            IUserService userService)
        {
            _paymentService = paymentService;
            _webHostEnvironment = webHostEnvironment;
            _itemService = itemService;
            _productService = productService;
            _orderService = orderService;
            _orderDetailService = orderDetailService;
            _userService = userService;
        }

        /*[HttpGet]
        public IActionResult Index()
        {
            var model = _paymentService.GetAll().Select(payment => new IndexPaymentViewModel
            {
                paymentID = payment.paymentID,
                userID = payment.userID,
                method = payment.method,
                nameOnCard = payment.nameOnCard,
                cardNumber = payment.cardNumber,
                expiration = payment.expiration,
                CVV = payment.CVV,
            }).ToList();
            return View(model);
        }*/
        [HttpGet]
        public IActionResult Index()
        {
            var model = _paymentService.GetAll().Select(payment => new TransactionViewModel
            {
                paymentID = payment.paymentID,
                //firstName = payment.firstName,
                //lastName = payment.lastName,
                //phoneNumber= payment.phone,
                totalPrice= payment.totalPrice,
                method = payment.method,
                nameOnCard = payment.nameOnCard,
                cardNumber = payment.cardNumber,
                expiration = payment.expiration,
                CVV = payment.CVV,
            }).ToList();
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var user = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            ApplicationUser tempUser = _userService.getbyID(user);
            var model = new TransactionViewModel
            {
                paymentID = Guid.NewGuid().ToString(),
                userID = user,
                listItem = _itemService.getUserItem(user),
                totalPrice = totalPriceCal(_itemService.getUserItem(user)),
                orderID = Guid.NewGuid().ToString(),
                firstName = tempUser.Fristname,
                lastName = tempUser.Lastname,
                address = tempUser.Address,
                phoneNumber = tempUser.Phone,
                email = tempUser.UserName,
            };
            return View(model);
        }
        public double totalPriceCal(IEnumerable<Item> listItem)
        {
            double totalPrice = 0;
            foreach (Item item in listItem)
            {
                totalPrice += _productService.GetById(item.productID).price * item.quantity;
            }
            return totalPrice;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TransactionViewModel model)
        {
            if (ModelState.IsValid)
            {
                var payment = new Payment
                {
                    paymentID = model.paymentID,
                    userID = model.userID,
                    method = model.method,
                    nameOnCard = model.nameOnCard,
                    cardNumber = model.cardNumber,
                    expiration = model.expiration,
                    CVV = model.CVV,
                    totalPrice = model.totalPrice,
                }; 

                var order = new Order
                {
                    orderID = model.orderID,
                    FirstName = model.firstName,
                    LastName = model.lastName,
                    Email = model.email,
                    Address = model.address,
                    Phone = model.phoneNumber,
                    paymentID = model.paymentID,
                    //listItem = _itemService.getUserItem(model.userID),
                    Total = model.totalPrice,
                };
                await _paymentService.CreateAsSync(payment);
                await _orderService.CreateAsSync(order);
                IEnumerable<Item> listItem = _itemService.getUserItem(model.userID);
                foreach (var item in listItem)
                {
                    var detail = new OrderDetail
                    {
                        orderID = model.orderID,
                        productID = item.productID,
                        productName = item.productName,
                        productPrice = item.productPrice,
                        quantity = item.quantity
                    };
                    await _orderDetailService.CreateAsSync(detail);
                }
                await _itemService.DeleteUserItem(model.userID);
                return RedirectToAction("Product","Product");
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Detail(string id)
        {
            var payment = _paymentService.GetById(id);
            if (payment == null)
            {
                return NotFound();
            }
            var model = new DetailTransactionViewModel
            {
                paymentID = payment.paymentID,
                userID = payment.userID,
                //firstName = payment.firstName,
                //lastName = payment.lastName,
                //email = payment.email,
                //address = payment.address,
                //phoneNumber = payment.phone,
                method = payment.method,
                nameOnCard = payment.nameOnCard,
                cardNumber = payment.cardNumber,
                expiration = payment.expiration,
                CVV = payment.CVV,
                totalPrice = payment.totalPrice,
                //listItem = _itemService.getUserItem(payment.userID),
            };
            return View(model);
        }
    }
}

MVC-model/Controllers/UserController.cs
using Entity;
using Microsoft.AspNetCore.Mvc;
using MVC_model.Models;
using Newtonsoft.Json;
using Service;
using Service.Implementation;
using System.Globalization;
using System.Security.Claims;

namespace MVC_model.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Home()
        {
            return View();
        }

        private IItemService _itemService;
        private IProductService _productService;
        private IWebHostEnvironment _webHostEnvironment;
        private IPaymentService _paymentService;
        public UserController(IProductService productService, IItemService itemService, IWebHostEnvironment webHostEnvironment, IPaymentService paymentService)
        {
            _productService = productService;
            _webHostEnvironment = webHostEnvironment;
            _itemService = itemService;
            _paymentService = paymentService;

        }

        [HttpGet]
        public IActionResult CartItem()
        {
            var user = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var model = new UserCartIndex
            {
                paymentID = Guid.NewGuid().ToString(),
                userID = user,
                listItem = _itemService.getUserItem(user),
                totalPrice = totalPriceCal(_itemService.getUserItem(user)),
            };
            return View(model);
        }

        public double totalPriceCal(IEnumerable<Item> listItem)
        {
            double totalPrice = 0;
            foreach (Item item in listItem)
            {
                totalPrice += _productService.GetById(item.productID).price * item.quantity;
            }
            return totalPrice;
        }

        /*[HttpGet]
        public IActionResult Index()
        {
            var user = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var model = _itemService.GetCart(_cartService.GetByUserId(user).shoppingCartID).Select(cartItem => new IndexCartViewModel
            {
                itemID = cartItem.cartID,
                productID = cartItem.product.productID,
                productName = cartItem.product.productName,
                brand = cartItem.product.brand,
                price = cartItem.product.price,
                Quantity = cartItem.quantity
            }).ToList();
            return View(model);
        }*/

        [HttpGet]
        public IActionResult AddToCart(int id)
        {
            var productTemp = _productService.GetById(id);
            if (productTemp == null)
            {
                return NotFound();
            }
            var user = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var model = new IndexProductViewModel
            {
                itemID = Guid.NewGuid().ToString(),
                productID = id,
                quantity = 1,
                userID = user,
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToCart(IndexProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (_itemService.CheckItem(model.userID, model.productID) == true)
                {
                    Item item = new Item
                    {
                        itemID = model.itemID,
                        product = _productService.GetById(model.productID),
                        quantity = model.quantity,
                        userID = model.userID,
                    };
                    await _itemService.CreateAsSync(item);
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
    }
}

MVC-model/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DCT1205</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/DCT1205.styles.css" asp-append-version="true" />*@
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="~/css/sidebars.css" rel="stylesheet">
    
</head>
<body>
    <nav class="navbar bg-body-tertiary bg-info" data-bs-theme="info">
        <div class="container-fluid">
            <a class="navbar-brand" asp-controller="User" asp-action="Home">
                <img src="~/images/Dotabg.jpg" alt="logo" width="120" height="60">
            </a>
            <div class="navbar-menu-wrapper bg-info d-flex align-items-center justify-content-end">
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit" style="color: snow;border: 1px solid #dee2e6;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                        </svg>
                    </button>
                </form>
                @*<i class="fa-solid fa-cart-shopping fa-2xl" style="color: #000000;"></i>*@
                @*<partial name="_LoginPartial" />*@
            </div>
        </div>
    </nav>

    <div class="container-fluid page-body-wrapper">
        <div class="flex-shrink-0 p-3" style="width: 280px;  border-right: 1px solid #d3d3d3;background-image: url(https://colorlib.com/etc/bootstrap-sidebar/sidebar-06/images/bg_1.jpg);">
            <ul class="list-unstyled ps-0">
                <li class="mb-1">
                    <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="false">
                        <span class="fa fa-home mr-3"></span>
                        Home
                    </button>
                    <div class="collapse" id="home-collapse">
                        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                            <li><a class="nav-link" asp-controller="Home" asp-action="Index">Adnin Hone</a></li>
                            <li><a class="nav-link" asp-controller="User" asp-action="Home">User Home</a></li>
                        </ul>
                    </div>
                </li>
                <li class="mb-1"> 
                    <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#product-collapse" aria-expanded="false">
                        Product
                    </button>
                    <div class="collapse" id="product-collapse">
                        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                            <li class="nav-item"><a class="nav-link" asp-controller="Product" asp-action="Create"> New Product</a></li>
                            <li class="nav-item"><a class="nav-link" asp-controller="Product" asp-action="Index"> All Produt</a></li>
                        </ul>
                    </div>
                </li>
                <li class="mb-1">
                    <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#payment-collapse" aria-expanded="false">
                        Payment
                    </button>
                    <div class="collapse" id="payment-collapse">
                        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                            <li class="nav-item"><a class="nav-link" asp-controller="Payment" asp-action="Index"> All Payment</a></li>
                        </ul>
                    </div>
                </li>
     
                <li class="mb-1">
                    <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#orders-collapse" aria-expanded="false">
                        Orders
                    </button>
                    <div class="collapse" id="orders-collapse">
                        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                            <li class="nav-item"><a class="nav-link" asp-controller="Order" asp-action="Index"> All Order</a></li>

                        </ul>
                    </div>
                </li>
                <li class="mb-1">
                    <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#role-collapse" aria-expanded="false">
                        Role
                    </button>
                    <div class="collapse" id="role-collapse">
                        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                            <li class="nav-item"><a class="nav-link" asp-controller="AppRoles" asp-action="Index">RoleList</a></li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="Identity" asp-page="/Account/Register">Register</a>
                            </li>

                        </ul>
                    </div>
                </li>

                <li class="border-top my-3"></li>
                <li class="mb-1">
                    <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">        
                            <strong>Admin</strong>
                    </button>
                    <div class="collapse" id="account-collapse">
                        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                            <li><a asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage" class="link-body-emphasis d-inline-flex text-decoration-none rounded">Profile</a></li>
                            <li>
                                <a class="btn btn-warning btn-outline-light me-2" href="#userHomePage">
                                    <form class="form-inline"  asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Home", "User", new { area = "" })">
                                        <button type="submit" class="nav-link btn btn-link text-dark">Sign out</button>
                                    </form>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
        

        <div class="main-panel">
            <div class="content-wrapper" style="background: white;">
                @RenderBody()
            </div>
            <footer class="footer" style="background: white;">
                <p> &copy; @DateTime.UtcNow.Year - MVC_model - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></p>
            </footer>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVC-model/Views/Shared/_LayoutUser.cshtml
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/carousel.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="~/css/carousel.css" rel="stylesheet" />
</head>
<body>
    <header class="p-3 text-bg-dark" style="background-color: #2b80ff !important;">
        <div id="userHomePage" class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <img src="~/images/Dotabg.jpg" alt="logo" width="120" height="60">
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a asp-controller="User" asp-action="Home" class="nav-link px-2 text-white">Home</a></li>
                    <li><a href="#carouselExampleInterval" class="nav-link px-2 text-white">Introduce</a></li>
                    <li><a href="#about" class="nav-link px-2 text-white">About</a></li>
                    <li><a asp-controller="Product" asp-action="Search" class="nav-link px-2 text-white">Product</a></li>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li><a class="nav-link px-2 text-white" asp-controller="Home" asp-action="Index">Admin</a></li>
                    }
              
                </ul>
                

                <form class="d-flex" role="search" action="/Product/Search" method="get" style="margin-right: 2rem;">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" value="@ViewData["CurrentFilter"]" name="searchString">
                    <button class="btn btn-outline-success" type="submit" style="color: snow;border: 1px solid #dee2e6;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                        </svg>
                    </button>
                </form>

                
                <div class="text-end">

                    @*----------------------------------------------------Don't delete this--------------------------------------------*@
                  
                    <button class="btn  me-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions"><i class="fa-solid fa-cart-shopping fa-2xl" style="color: #000000;"></i></button>
                    <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">
                        <div class="offcanvas-header">
                            <h5>Shopping Cart</h5>
                            <span class="badge bg-primary rounded-pill">3</span>
                            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                        </div>
                        <div class="offcanvas-body">
                                <ul class="list-group mb-3">
                                    <li class="list-group-item d-flex justify-content-between lh-sm" style="text-align: justify;">
                                            <div>
                                                <h6 class="my-0">Nike T-shirt</h6>
                                                <small class="text-body-secondary">Quantity: 2</small>
                                            </div>
                                            <span class="text-body-secondary">$12</span>
                                    </li>
                                    <li class="list-group-item d-flex justify-content-between lh-sm" style="text-align: justify;">
                                        <div>
                                            <h6 class="my-0">Second product</h6>
                                            <small class="text-body-secondary">Brief description</small>
                                        </div>
                                        <span class="text-body-secondary">$8</span>
                                    </li>
                                    <li class="list-group-item d-flex justify-content-between lh-sm" style="text-align: justify;">
                                        <div>
                                            <h6 class="my-0">Third item</h6>
                                            <small class="text-body-secondary">Brief description</small>
                                        </div>
                                        <span class="text-body-secondary">$5</span>
                                    </li> 
                                    <li class="list-group-item d-flex justify-content-between" style="text-align: justify;">
                                        <span>Total (USD)</span>
                                        <strong>$20</strong>
                                    </li>
                            </ul>
                            <button class="w-100 btn btn-primary btn-lg" type="submit">
                                <a class="nav-link" asp-controller="Payment" asp-action="Create" style="color: white">Continue to checkout</a>      
                            </button>  
                        </div>
                    </div>
                    

                    @if (SignInManager.IsSignedIn(User))
                    {
                        <a asp-action="CartItem" asp-controller="User" class="btn btn-ouline-dark" type="submit">
                            <i class="fa-solid fa-cart-shopping fa-2xl" style="color: #000000;"></i>
                            Cart
                            <span id="badge" class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                        </a>

                        <button type="button" class="btn btn-outline-light me-2">
                            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">
                                <i class="fa-solid fa-user fa-xl" style="color: #ffffff;"></i>
                            </a>
                        </button>
                        
                        <a class="btn btn-warning btn-outline-light me-2">
                            <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Home", "User", new { area = "" })">
                                <button type="submit" class="nav-link btn btn-link text-dark"><i class="fa-solid fa-right-from-bracket fa-xl" style="color: #ffffff;"></i></button>
                            </form>
                        </a>  
                    }
                    else
                    {
                        <button type="button" class="btn btn-outline-light me-2">
                            <a class="nav-link text-white" asp-area="Identity" asp-page="/Account/Register">Register</a>
                        </button>
                        <button type="button" class="btn btn-warning">
                            <a class="nav-link text-white" asp-area="Identity" asp-page="/Account/Login">Login</a>
                        </button>
                    }
                </div>

            </div>
        </div>
    </header>
    <main>
        <div class="content-wrapper" style="padding-left: 3rem; padding-right: 3rem;">
            @RenderBody()
        </div>


        <footer class="container">
            <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
                <p> &copy; @DateTime.UtcNow.Year - MVC_model - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></p>
                <ul class="list-unstyled d-flex">
                    <li class="ms-3"><a class="link-body-emphasis" href="#"><i class="fa-brands fa-facebook fa-xl" style="color: #000000;"></i></a></li>
                    <li class="ms-3"><a class="link-body-emphasis" href="https://github.com/YangTris/MVC-model"><i class="fa-brands fa-github fa-xl" style="color: #000000;"></i></a></li>
                </ul>
            </div>
        </footer>
    </main>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)


    <script>
        $('input.input-qty').each(function () {
            var $this = $(this),
                qty = $this.parent().find('.is-form'),
                min = Number($this.attr('min')),
                max = Number($this.attr('max'))
            if (min == 0) {
                var d = 0
            } else d = min
            $(qty).on('click', function () {
                if ($(this).hasClass('minus')) {
                    if (d > min) d += -1
                } else if ($(this).hasClass('plus')) {
                    var x = Number($this.val()) + 1
                    if (x <= max) d += 1
                }
                $this.attr('value', d).val(d)
            })
        })

        $(".alertLogin").click(function () {
            alert("please login before purchase")
        });
        sessionStorage.setItem("searchString", @ViewData["CurrentFilter"])
        let searchString = sessionStorage.getItem("searchString");
    </script>
</body>
</html>